# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               A PROGRAMMER'S DILEMMA
tagline:             'TECH BLOG'
description:         'Wanna say HI? Drop in a <a href="http://ajish097@gmail.com/">message</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
gems: [jekyll-paginate]
#      -jekyll-gist

# About/contact
author:
  name:              Ajish Athrayil
  url:               https://twitter.com/mdo
  email:             ajish097@gmail.com

# Custom vars
version:             1.0.0
